spring.application.name=reservas-backend
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=sql
spring.jpa.hibernate.ddl-auto=update
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLongForJWT




