spring.application.name=reservas-backend
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=sql
spring.jpa.hibernate.ddl-auto=update
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLongForJWT

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000


