spring.application.name=reservas-backend
spring.datasource.url=jdbc:postgresql://localhost:5435/g1-reservation
spring.datasource.username=postgres
spring.datasource.password=soledad
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=sql